export const StatusProduto = {
  ATIVO: 'ATIVO',
  EXCLUIDO: 'EXCLUIDO',
} as const;

export const CategoriaProduto = {
  Livro: 'LIVRO',
  Disco: 'DISCO',
  CD: 'CD',
  DVD: 'DVD',
  Revista: 'REVISTA',
  Quadrinhos: 'QUADRINHOS',
} as const;

export const EstadoConservacaoProduto = {
  Novo: 'NOVO',
  Seminovo: 'SEMINOVO',
  Usado: 'USADO',
} as const;

export const GeneroProduto = {
  LIVRO: [
    'Infantil',
    'Romance',
    'Drama',
    'Poema/Poesia',
    'Mistério',
    'Policial',
    'Terror/Suspense',
    'Horror',
    'Ficção Científica',
    'Fantasia',
    'Ação e Aventura',
    'Histórico',
    'Didático',
    'Biografia',
    'Autoajuda',
    'Gastronomia',
    'Religião',
    'Mangá',
  ],
  QUADRINHOS: [
    'Infantil',
    'Romance',
    'Drama',
    'Poema/Poesia',
    'Mistério',
    'Policial',
    'Terror/Suspense',
    'Horror',
    'Ficção Científica',
    'Fantasia',
    'Ação e Aventura',
    'Histórico',
    'Didático',
    'Biografia',
    'Autoajuda',
    'Gastronomia',
    'Religião',
    'Mangá',
  ],
  REVISTA: [
    'Variedades',
    'Notícias',
    'Reportagem',
    'Publicidade',
    'Propaganda',
    'Entrevista',
    'Resenha',
    'Artigos Científicos',
  ],
  DISCO: [
    'Rock',
    'MPB',
    'Funk',
    'Forró',
    'Sertanejo',
    'Pagode',
    'Samba',
    'Pop',
    'K-pop',
    'Música Clássica',
    'Gospel',
    'Blues',
    'Jazz',
    'Eletrônica',
    'Hip-hop',
    'Country',
    'Reggae',
  ],
  CD: [
    'Rock',
    'MPB',
    'Funk',
    'Forró',
    'Sertanejo',
    'Pagode',
    'Samba',
    'Pop',
    'K-pop',
    'Música Clássica',
    'Gospel',
    'Blues',
    'Jazz',
    'Eletrônica',
    'Hip-hop',
    'Country',
    'Reggae',
  ],
  DVD: [
    'Infantil',
    'Romance',
    'Drama',
    'Poema/Poesia',
    'Mistério',
    'Policial',
    'Terror/Suspense',
    'Horror',
    'Ficção Científica',
    'Fantasia',
    'Ação e Aventura',
    'Histórico',
    'Didático',
    'Biografia',
    'Autoajuda',
    'Gastronomia',
    'Religião',
    'Rock',
    'MPB',
    'Funk',
    'Forró',
    'Sertanejo',
    'Pagode',
    'Samba',
    'Pop',
    'K-pop',
    'Música Clássica',
    'Gospel',
    'Blues',
    'Jazz',
    'Eletrônica',
    'Hip-hop',
    'Country',
    'Reggae',
  ],
} as const;
